package:
  name: evg
  version: 1.1.4

source:
  path: .

requirements:
  build:
    - cmake >=3.12
    - gcc >=7.3.0
    - python =3.9
    - zlib

  run:
    - cmake >=3.12
    - gcc >=7.3.0
    - python =3.9
    - zlib
    - tabix
    - bwa
    - samtools
    - vg
    - graphaligner
    - paragraph
    - bayestyper
    - graphtyper
    - kmc
    - pangenie

channels:
    - kdm801
    - bioconda
    - defaults
    - conda-forge

about:
  home: https://github.com/JiaoLab2021/EVG
  license: MIT
  summary: A comprehensive benchmark of graph-based genetic variant genotyping algorithms on plant genomes for creating an accurate ensemble pipeline

extra:
  recipe-maintainers:
    - duzezhen
